In [5]:
import numpy as np
import random
import matplotlib 
import projet

Partie 1:

In [6]:
p=projet.estim_prob()
print(p)

[[0.66666667 0.33333333 0.        ]
 [0.         0.83333333 0.16666667]
 [0.         0.         1.        ]]


In [8]:
fichier=np.loadtxt('data_exo1.txt')
n=projet.proba_transition(fichier)
print(n)

[[0.92435703 0.07564297 0.        ]
 [0.         0.93527508 0.06472492]
 [0.         0.         1.        ]]


Partie 2:

In [9]:
matrice=np.array([[0.92,0.08,0],[0,0.93,0.07],[0,0,1]])
print(matrice)
if projet.verif_stoch(matrice):
  print("La matrice est stochastique")
else:
  print("La matrice n'est pas stochastique")

[[0.92 0.08 0.  ]
 [0.   0.93 0.07]
 [0.   0.   1.  ]]
La matrice est stochastique
